In [5]:
import torch

In [6]:
a = torch.rand(3,4)

In [7]:
a

tensor([[0.1020, 0.6802, 0.5267, 0.7187],
        [0.9280, 0.0054, 0.1885, 0.6343],
        [0.1595, 0.1838, 0.8027, 0.1741]])

In [9]:
f, s = torch.max(a, 1)

In [10]:
f

tensor([0.7187, 0.9280, 0.8027])

In [11]:
s

tensor([3, 0, 2])

In [12]:
b = torch.tensor([3,2,0])

In [13]:
b == s

tensor([ True, False, False])

In [14]:
(b==s).squeeze()

tensor([ True, False, False])

In [15]:
c = (b==s).squeeze()

In [16]:
c[0]

tensor(True)

In [17]:
c[0].item()

True

In [18]:
5 + c[0].item()

6

In [1]:
import torch

In [2]:
x = torch.randn(2, 3)

In [3]:
x

tensor([[-0.8849,  0.2714,  1.6983],
        [-0.3381, -0.3767, -0.1759]])

In [4]:
x.shape

torch.Size([2, 3])

In [6]:
x.unsqueeze_(0)

tensor([[[-0.8849,  0.2714,  1.6983],
         [-0.3381, -0.3767, -0.1759]]])

In [7]:
x

tensor([[[-0.8849,  0.2714,  1.6983],
         [-0.3381, -0.3767, -0.1759]]])

In [8]:
x.shape

torch.Size([1, 2, 3])

In [9]:
torch.transpose(x, 1,2)

tensor([[[-0.8849, -0.3381],
         [ 0.2714, -0.3767],
         [ 1.6983, -0.1759]]])

In [10]:
x.shape

torch.Size([1, 2, 3])

In [14]:
x.view(1,-1)

tensor([[-0.8849,  0.2714,  1.6983, -0.3381, -0.3767, -0.1759]])