## PyTorch 是什么？
基于python 的科学计算包，服务于一下两种场景：

    1. 作为numpy的替代品，可以使用GPU的强大计算能力
    2. 提供最大的灵活性和高速的深度学习研究平台

## 一、张量

In [1]:
import torch

### 1.1 创建一个没有初始化的5*3 矩阵

In [2]:
x = torch.empty(5, 3)

In [3]:
x

tensor([[4.1327e-39, 8.9082e-39, 9.8265e-39],
        [9.4592e-39, 1.0561e-38, 1.0653e-38],
        [1.0469e-38, 9.5510e-39, 1.0286e-38],
        [1.0194e-38, 9.6429e-39, 9.2755e-39],
        [8.4490e-39, 8.7245e-39, 1.0102e-38]])

### 1.2 创建一个随机初始化的5*3矩阵

In [4]:
x_rand = torch.rand(5,3)

In [5]:
x_rand

tensor([[0.2945, 0.3110, 0.4350],
        [0.3848, 0.5178, 0.9291],
        [0.2742, 0.5910, 0.5477],
        [0.7936, 0.7822, 0.8409],
        [0.8563, 0.3490, 0.9255]])

### 1.3 构造一个填满0且数据类型为long的矩阵

In [6]:
x_zero = torch.zeros(3,4, dtype=torch.long)

In [7]:
x_zero

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

### 1.4 使用python 列表直接构造矩阵

In [8]:
x_list = torch.tensor([[1,2,5],[35,5,9]])

In [9]:
x_list

tensor([[ 1,  2,  5],
        [35,  5,  9]])

### 1.5 根据现有tensor 构造新 tensor 

In [10]:
x_new = x_list.new_ones(2,3)

In [11]:
x_new

tensor([[1, 1, 1],
        [1, 1, 1]])

In [12]:
x_new_rand = torch.rand_like(x_list, dtype=torch.float)

In [13]:
x_new_rand

tensor([[0.4119, 0.2924, 0.5587],
        [0.0059, 0.4509, 0.2214]])

### 1.6 获取张量形状（torch.Size 本质还是tuple， 所以支持tuple的一切操作）

In [14]:
x_rand.size()

torch.Size([5, 3])

In [15]:
x_list.size()

torch.Size([2, 3])

In [16]:
x_list.size()[1]

3

## 二、 张量运算

In [17]:
y_rand = torch.rand(5, 3)

In [18]:
y_rand

tensor([[0.7577, 0.7006, 0.2971],
        [0.6916, 0.1776, 0.1760],
        [0.0766, 0.4446, 0.6756],
        [0.0939, 0.1359, 0.0139],
        [0.7589, 0.9828, 0.8331]])

> 加法： 形式一

In [19]:
x_rand + y_rand

tensor([[1.0522, 1.0116, 0.7321],
        [1.0765, 0.6954, 1.1051],
        [0.3508, 1.0356, 1.2233],
        [0.8876, 0.9181, 0.8547],
        [1.6152, 1.3318, 1.7586]])

> 加法： 形式二

In [20]:
torch.add(x_rand, y_rand)

tensor([[1.0522, 1.0116, 0.7321],
        [1.0765, 0.6954, 1.1051],
        [0.3508, 1.0356, 1.2233],
        [0.8876, 0.9181, 0.8547],
        [1.6152, 1.3318, 1.7586]])

> 加法： 原位/原地操作（in-place）

In [21]:
# adds x_rand to y_rand
y_rand.add_(x_rand)

tensor([[1.0522, 1.0116, 0.7321],
        [1.0765, 0.6954, 1.1051],
        [0.3508, 1.0356, 1.2233],
        [0.8876, 0.9181, 0.8547],
        [1.6152, 1.3318, 1.7586]])

In [22]:
y_rand

tensor([[1.0522, 1.0116, 0.7321],
        [1.0765, 0.6954, 1.1051],
        [0.3508, 1.0356, 1.2233],
        [0.8876, 0.9181, 0.8547],
        [1.6152, 1.3318, 1.7586]])

> 任何一个就地改变的张量操作后面都固定一个 _ 。 例如 x.copy_(y), x.t_() 将更改x。

###  2.1 pytoch 的索引操作（与numpy一样）

In [23]:
x_rand

tensor([[0.2945, 0.3110, 0.4350],
        [0.3848, 0.5178, 0.9291],
        [0.2742, 0.5910, 0.5477],
        [0.7936, 0.7822, 0.8409],
        [0.8563, 0.3490, 0.9255]])

In [24]:
x_rand[:,1]

tensor([0.3110, 0.5178, 0.5910, 0.7822, 0.3490])

### 2.2 tensor 改变形状， 使用 torch.view

In [25]:
x_view = torch.rand(4,4)

In [26]:
x_view

tensor([[0.3482, 0.1004, 0.0265, 0.2144],
        [0.9224, 0.6832, 0.8753, 0.1543],
        [0.7415, 0.7799, 0.3756, 0.9045],
        [0.3204, 0.2211, 0.5428, 0.7762]])

In [27]:
x_view.view(16)

tensor([0.3482, 0.1004, 0.0265, 0.2144, 0.9224, 0.6832, 0.8753, 0.1543, 0.7415,
        0.7799, 0.3756, 0.9045, 0.3204, 0.2211, 0.5428, 0.7762])

In [28]:
x_view.view(-1, 2)

tensor([[0.3482, 0.1004],
        [0.0265, 0.2144],
        [0.9224, 0.6832],
        [0.8753, 0.1543],
        [0.7415, 0.7799],
        [0.3756, 0.9045],
        [0.3204, 0.2211],
        [0.5428, 0.7762]])

In [29]:
x_view.view(2,2,-1)

tensor([[[0.3482, 0.1004, 0.0265, 0.2144],
         [0.9224, 0.6832, 0.8753, 0.1543]],

        [[0.7415, 0.7799, 0.3756, 0.9045],
         [0.3204, 0.2211, 0.5428, 0.7762]]])

In [30]:
x_view.view(2,2,2,-1)

tensor([[[[0.3482, 0.1004],
          [0.0265, 0.2144]],

         [[0.9224, 0.6832],
          [0.8753, 0.1543]]],


        [[[0.7415, 0.7799],
          [0.3756, 0.9045]],

         [[0.3204, 0.2211],
          [0.5428, 0.7762]]]])

### 2.3 桥接 numpy 

> 将一个torch 张量转换为一个 numpy 数组是轻而易举的事情，反之亦然
> torch 张量与 numpy 数组将共享他们的底层内存位置， 因此当一个改变时， 另外也会改变

In [31]:
a = torch.ones(5)

In [32]:
a

tensor([1., 1., 1., 1., 1.])

In [33]:
b = a.numpy()

In [34]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [35]:
# 验证tensor与numpy公用内存
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [36]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

### 2.4 将numpy 数组转换为 torch 张量

In [37]:
import numpy as np

In [38]:
a_numpy = np.ones(5)

In [39]:
a_numpy

array([1., 1., 1., 1., 1.])

In [40]:
b_tensor = torch.from_numpy(a_numpy)

In [41]:
b_tensor

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

> cup上所有张量（CharTensor除外）都支持与Numpy的相互转换。

### 2.5 CUDA上的张量

In [42]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y_cuda = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y_cuda

In [43]:
z

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [44]:
z.to('cpu', torch.double)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)